config/routes.rb
Scholarships::Application.routes.draw do
  resources :scores


  resources :references


  resources :applications do
    collection do
      post :edit_multiple
    end
  end

  match '/applications/:id/sign', to: 'applications#sign', as: :sign_application
  match '/applications/:id/unsign', to: 'applications#unsign', as: :unsign_application
  match '/reset', to: 'applications#reset', as: :reset_applications_action


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  resources :users
  match '/references/send_email' => 'references#send_reference_request'
  match '/references/:id', to: 'references#resend', via: :post
  match '/references/token/:token' => 'references#edit'
  
 # match '/login' => "devise/sessions#new"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#  provider               :string(255)
#  uid                    :string(255)
#

class User < ActiveRecord::Base
  rolify
  has_and_belongs_to_many :applications
  has_many :references
  has_many :scores

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  after_create :default_role_and_create_blank_application

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name

  REVIEWERS = ['dcmanueljr@gmail.com','dtepfer@ameritech.net','sthoron@aol.com','swansj@gmail.com','dsanchez@pflag.org','jennifersavage@pflagtricities.org',
                'mosestorreblanca@gmail.com','katynelsen71@gmail.com','lynne_490@hotmail.com','madams4@hotmail.com','kt6565@yahoo.com','hrickerl1@gmail.com',
                'laurie.mayers@gmail.com','thom3308@msn.com','arthurfreeheart1@gmail.com','patpoynter@yahoo.com', 'sherrythompsonharrold@gmail.com', 'tamiekaufman@hotmail.com',
                'pflagyumasecretary@yahoo.com', 'cztwins@hotmail.com', 'hughes1985@hotmail.com', 'taramitchell@gmail.com']

  DEADLINE = Date::strptime(ENV['DEADLINE'],"%m-%d-%Y")

  def is?(role)
    self.has_role?(role)
  end

  def application
    if self.has_role? :student
      Application.find_by_uid(self.id)
    end
  end


  def incomplete_application?
    !@email.in? REVIEWERS and self.application.incomplete? unless self.application.blank?
  end

  def active_for_authentication?
    super and !(self.is? :student and Date.today > DEADLINE )
  end

  def inactive_message
    Date.today <= DEADLINE ? super : :deadline_has_already_passed
  end

  private
  def default_role_and_create_blank_application
    domain = /@(.+$)/.match(self.email)[1]
    admin = domain.casecmp("pflag.org") != 0 ? false : true
#    admin = false #no auto admin
    reviewer = self.email.downcase.in? User::REVIEWERS #|| domain.casecmp("pflag.org") == 0 # add PFLAG.org as reviewers

    if reviewer
      remove_role :student
      add_role :reviewer
    elsif admin
      add_role :admin
    else
      add_role :student
      self.applications.push Application.new({:applicant_user_id => self.id}) unless Time.now.to_date > Date::strptime(ENV["DEADLINE"],"%m-%d-%Y")

    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  check_authorization :unless => :devise_controller?

  def after_sign_in_path_for(resource)
    redirect_path = root_path
    if current_user.is? :student
      if (Application.find_by_uid current_user.id).blank?
        redirect_path = new_application_path
      else
        redirect_path = edit_application_path Application.find_by_uid current_user.id
      end
    end
    if current_user.is? :admin
        if Time.now.to_date > Date::strptime(ENV["DEADLINE"],"%m-%d-%Y")
            redirect_path = applications_path(:transcript => 1, :signed => 1, :reference => 1, :essay => 1)
        else
            redirect_path = applications_path
        end
    elsif current_user.is? :reviewer
      redirect_path = applications_path
    end
    redirect_path
  end


  rescue_from CanCan::AccessDenied do |exception|
  	if current_user.nil?
      session[:next] = request.fullpath
      puts session[:next]
      redirect_to root_url, :alert => "You have to log in to continue."
    else
      #render :file => "#{Rails.root}/public/403.html", :status => 403
      if request.env["HTTP_REFERER"].present?
        redirect_to :back, :alert => exception.message
      else
        redirect_to root_url, :alert => exception.message
      end
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

def us_states
    [
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY'],
      ['ZZ', 'ZZ']
    ]
  end

  def us_states_long
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['U.S. Virgin Islands', 'VI'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY'],
      ['Non-US', 'ZZ']
    ]
  end

  def flash_message(flash)
    flash_html = ""
    flash.each do |name, msg|
      if msg.is_a?(String)
        flash_html += "<div class=\"alert alert-dismissable alert-" + (name == :notice ? "success" : "danger") + "\"><a class=\"close\" data-dismiss=\"alert\">&times;</a>" + (content_tag :div, msg, :id => "flash_#{name}")
      end
    end
    flash_html.html_safe
  end

  def glyph(g,*opts)
    options = {:class => "glyphicon glyphicon-"+g}
    opts.each do |o|
      options[o.keys[0]] = o.values[0]
    end
    content_tag(:i,"",options)
  end

  def rating_row (field,f)
    html = "<tr>"
    html += "<td>"
    html += f.label(field).html_safe
    html += "</td>"
    Reference::RATING_SCALE.each do |rating|
      html += "<td>"
      html += f.radio_button(field, rating[1]).html_safe
      html += "</td>"
    end
    html += "</tr>"
    html.html_safe
  end

  def deadline_passed?
    Time.now.to_date > Date::strptime(ENV["DEADLINE"],"%m-%d-%Y")
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
	def format_field(type,value)
      display = "No Response"
	  case  type
	  when :boolean
	  	display = t(value.to_s) unless value.nil?
	  when :text
	  	display = "<div class='well'>" + (value || "") + "</div>" unless value.blank?
	  	display = display.html_safe
	  when :string
	  	display = value.html_safe unless value.blank?
	  when :date
	    display = l value
	  when :datetime
	  	display = l value
	  when :transcript
		display = (link_to "Open Transcript", @application.transcript.url, :target => "_BLANK").html_safe unless value.blank?
	  else
	  	display = value
      end

    display
	end

	def reset_database
		Application.all.each{|a| a.destroy}
		Reference.all.each{|r| r.destroy }
		Score.all.each{|s| s.destroy }
		User.with_role(:student).each{|u| u.destroy }
		puts "Done. Don't forget to update the application date ENV['DEADLINE']"
	end

end

app/views/applications/_reference.html.erb
<dl>
  <dt>Name:</dt>
  <dd><%= @reference.name %></dd>
</dl>

<dl>
  <dt>Email:</dt>
  <dd><%= @reference.email %></dd>
</dl>

<dl>
  <dt>Phone number:</dt>
  <dd><%= @reference.phone_number %></dd>
</dl>

<dl>
  <dt>How long have you known:</dt>
  <dd><%= @reference.how_long_have_you_known %></dd>
</dl>

<dl>
  <dt>Relationship:</dt>
  <dd><%= @reference.relationship.html_safe unless @reference.relationship.blank? %></dd>
</dl>

<dl>
  <dt>References essay:</dt>
  <dd><%= @reference.references_essay.html_safe unless @reference.references_essay.blank? %></dd>
</dl>

app/views/applications/edit.html.erb
<h1>PFLAG National Scholarship Application</h1>

<%= render 'form' %>

app/views/applications/index.csv.erb
"user id","email","application
url","name","average","scores","scores_variance","first_generation","identify_lgbt","stem","score_count","completed references","reference_email","signed?","blank_fields"
<% @applications.each do |a| %>
<%= "#{a.user.id},#{a.user.email}" unless a.user.blank? %>,http://pflag-scholarship.herokuapp.com/applications/<%= a.id %>,"<%= a.name %>",<%= a.average_score %>,<%= a.scores.collect { |k| k.normalized_score.to_s }.join(", ") %>,<%= a.scores_variance%>,<%=a.first_generation%>,<%=a.identify_lgbt%>,<%= a.stem? %>,<%=a.scores.count if a.scores.present?%>,<%=a.references.completed.count %>,<%=a.references.first.email if a.references.first.present? %>,<%= a.signed?%>,<%= a.blank_fields_count %>
<% end %>

app/views/applications/index.html.erb
<h1>Applications</h1>


<% if current_user.is? :admin %>

<div class="well">
<%= simple_form_for '', :url => applications_path, :method => :get, :html => { :class => "form-inline", :role => "form" } do |f| %>
  <%= f.input :name, :label => false, :wrapper_html => {:class=> "col-md-3"}, input_html: { value: params[:name], :placeholder => "Name"} %>
  <%= f.input :email, :label => false, :wrapper_html => {:class=> "col-md-3"}, input_html: { value: params[:email], :placeholder => "Email"} %>
  Transcript <%= f.check_box :transcript, :checked => (params[:transcript] == '1') %> &nbsp;
  Signed <%= f.check_box :signed, :checked => (params[:signed] == '1') %> &nbsp;
  Essay <%= f.check_box :essay, :checked => (params[:essay] == '1') %> &nbsp;
  Reference <%= f.check_box :reference, :checked => (params[:reference] == '1') %> &nbsp;
<!--  Completed <%= f.check_box :completed, :checked => (params[:completed] == '1') %> &nbsp;-->
  <%= f.button :submit, 'Search', :class => "btn btn-primary" %>
<p><br>
Showing <%= @applications.count.is_a?(Integer) ? @applications.count : @applications.count.length %> records
</p>
</div>

<%end%>
<%end%>
<%= simple_form_for '', :url => edit_multiple_applications_path, :html => { :class => "form-inline", :role => "form" } do |f| %>
<% if current_user.is? :admin %>
<div class="well">
    <%= f.input :reviewer, :collection => User.with_any_role(:admin,:reviewer).sort_by(&:name), required: true, :label_html => {:style => "display: none;"}, :wrapper_html => {:class=> "col-md-3"}, prompt: "Assign reviewer..." %>
Replace Reviewers <%= f.check_box :replace_reviewers %> &nbsp;
  <%= f.button :submit, 'Apply', :class => "btn btn-primary" %>
    <%= f.input :transcript, as: :hidden, :input_html => {value: params['transcript']}%>
    <%= f.input :reference, as: :hidden, :input_html => {value: params['reference'] }%>
    <%= f.input :completed, as: :hidden, :input_html => {value: params['completed'] }%>
    <%= f.input :signed, as: :hidden, :input_html => {value: params['signed'] }%>
    <%= f.input :essay, as: :hidden, :input_html => {value: params['essay'] }%>

</div>
<% end %>
<%= will_paginate @applications, renderer: BootstrapPagination::Rails %>

<table class="table table-striped">
  <tr>
    <% if current_user.is? :admin %>
    <th><%= check_box_tag 'select_all_application_id', '', false %></th>
    <%end %>
    <th>Name</th>
    <% if current_user.is? :admin %>
        <th></th>
    <% end %>

    <% if current_user.is? :admin and !@review %>
    <th>Complete?</th>
    <th>Signed?</th>
    <th>Transcript?</th>
    <th>Reference?</th>
    <th>Blank<br>Fields?</th>
    <th>Reviewers</th>
    <th><%= link_to "Average Score", applications_path(:sort => 'score') %></th>
    <% end %>
    <% if current_user.is? :admin and @review %>
    <th><%= link_to "STEM?", params[:sort] == 'stem' ? applications_path(:sort => 'score') : applications_path(:sort => 'stem') %></th>
    <th><%= link_to "First Gen", params[:sort] == 'first_generation' ? applications_path(:sort => 'score') : applications_path(:sort => 'first_generation') %></th>
    <th>LGBT?</th>
    <th>Supporter?</th>
    <th>State</th>
    <th>Std Dev.</th>
    <th>Range</th>

    <th><%= link_to "Average Score", applications_path %></th>

    <% end %>
    <th>Scored?</th>
  </tr>
<%= hidden_field_tag :page, params[:page] %>
<% @applications.each do |application| %>
  <tr>
    <% if current_user.is? :admin %>
    <td><%= check_box_tag 'application_ids[]', application.id, false %></td>
    <%end%>
    <td><%=link_to glyph("file"), application_path(application) %>
     <% if can? :show, :user %>
      <%= link_to application.applicant.name, application.applicant unless application.applicant.blank? %>
     <% else %>
      <%= application.applicant.name unless application.applicant.blank? %>
     <% end %>
    </td>

    <% if current_user.has_role? :admin %>

    <td>
    <%= link_to glyph("pencil"), edit_application_path(application) if can? :edit, application %>
    <%= link_to glyph("trash"), application, method: :delete, data: { confirm: 'Are you sure?' } if can? :delete, application %>
    </td>
    <%end %>

    <% if current_user.is? :admin and !@review %>

    <td><%= application.incomplete? ? glyph("remove") : glyph("ok") %></td>
    <td><%= application.signed? ? glyph("ok") : glyph("remove") %></td>
    <td><%= application.transcript? ?
          (link_to glyph("ok"), edit_application_path(application, :anchor => "transcript")) :
          glyph("remove") %> </td>
    <td>
      <%= glyph("exclamation-sign",:title => "Multiple References") if application.references.completed.count > 1 %>
      <% reference = application.references.completed.first %>
      <%= link_to glyph("ok"), edit_reference_path(reference) unless reference.blank?  %>
      <% if current_user.is? :admin %>
      <%= link_to glyph("lock"), reference.token_url, title: "Private Reference Link for Manually emailing to reference" unless reference.blank? %>
      <% end %>
    </td>
    <td><span title="<%=application.blank_fields.join(", ") %>"><%= application.blank_fields_count %></span></td>
    <td><%= application.reviewers.map{|r| a = application.scores.find_by_user_id(r.id); "#{r.name}"+ ((" (#{a.total})" unless a.blank?) or "")}.join(", ") unless application.reviewers.blank? %></td>
    <td><%= number_with_precision application.average_score, :precision => 2 unless application.average_score.blank? %></td>
    <% end %>
    <% if current_user.is? :admin and @review %>
    <td><%= application.stem? ? glyph("ok") : glyph("remove") %></td>
    <td><%= application.first_generation? ? glyph("ok") : glyph("remove") %></td>
    <td><%= application.identify_lgbt? ? glyph("ok") : glyph("remove") %></td>
    <td><%= application.identify_supporter? ? glyph("ok") : glyph("remove") %></td>


    <td><%= application.state %></td>
    <td><%= number_with_precision application.scores_standard_deviation, :precision => 2 unless application.scores.blank? %></td>
    <td><%= number_with_precision application.scores_range, :precision => 2 unless application.scores.blank? %></td>
    <td><span title="<%= application.scores.map{|h| number_with_precision h.total, :precision => 2}.join(", ")  %>"><%= number_with_precision application.average_score, :precision => 2 unless application.average_score.blank? %></span></td>

    <% end %>

    <td><% application.scores.accessible_by(current_ability).each do |s| %>
      <%= glyph("ok") unless current_user.is? :admin%>
      <%= link_to glyph("pencil"), edit_score_path(s.id) %>
      <% end %>
      <% if application.scores.accessible_by(current_ability).count == 0 %>
        <%= glyph("exclamation-sign",:title => "Needs Scoring") %>
        <%= link_to "New Score", new_score_path(:application_id => application.id) %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<%= will_paginate @applications, renderer: BootstrapPagination::Rails %>
<% end %>
<br />

    <%= link_to 'New Application', new_application_path, :class => 'btn btn-primary' unless (current_user.has_role? :student or current_user.has_role? :reviewer) && @applications.length > 0 %>


<% if current_user.has_role? :admin %>
    <%= link_to "Download CSV", applications_path(params.merge(:format => "csv")), :class => 'btn btn-primary'  %>
<%end%>

app/views/applications/new.html.erb
<h1>Scholarship Application</h1>

<%= render 'form' %>

app/views/applications/reset.html.erb
<h1>Are you sure?</h1>

<h2>STOP! Click here if you're really sure that you want to delete everything.</h2>
<br>
<div>
  <%= link_to "Delete All Applications, Users and References", reset_applications_action_path(confirm:true, students:true), { class: "btn btn-danger"} %>
</div>
<br/>
<div>
  <%= link_to "Delete All Reviewers", reset_applications_action_path(confirm:true, reviewers:true), { class: "btn btn-danger"} %>

</div>

app/views/applications/show.html.erb
<% if params[:iframe] != '1' %>
<h2>Scoring</h2>
<% @application.scores.accessible_by(current_ability).each do |s| %>
      <%= link_to (glyph("pencil") + "Edit Score").html_safe, edit_score_path(s.id), :target => "_BLANK" %>
      <% end %>
      <% if @application.scores.accessible_by(current_ability).count == 0 %>
        <%= glyph("exclamation-sign") %>
        <%= link_to "New Score", new_score_path(:application_id => @application.id), :target => "_BLANK" %>
      <% end %>
<% end %>
<h2>Application</h2>
<div>
  <b><%= t "simple_form.labels.user.name" %></b>
</div>
<div>
	<%= @application.user.name unless @application.user.blank? %>
</div>

<% applications_fields_for_reviewers = ["are_you_a_graduating_high_school_senior",
"identify_lgbt","out_and_open","supportive_parents","identify_supporter",
"how_did_you_learn_about_the_scholarship","how_did_you_learn_explanation",
"name_of_high_school","cumulative_gpa","transcript_file_name",
"honors_or_awards","please_lists_schools_where_you_will_be_applying","major",
"admission_status","first_generation","first_generation_american","stem","why_do_you_want","describe_community_service_activities",
"employment_history","essay"] %>

<% applications_fields_for_reviewers.each do |name| %>
<div style="margin-top: 15px;">
  <b> <%=
        I18n.translate("simple_form.labels.application.#{name}_html", :default => t("simple_form.labels.application.#{name}")).html_safe
    %></b>
</div>
<div>
	<% if name.eql? "transcript_file_name" %>
	  <% type = :transcript %>
	<% elsif name.eql? "reference_id" %>
	  <% type = :reference %>
	<% else %>
      <% type = @application.column_for_attribute(name).type %>
	<% end %>
	<% value = @application[name.to_sym] %>
	<%= format_field(type,value) %>

</div>
<% end %>

<div class="well">
	<h2>Reference</h2>
	<%= render 'references/fields' unless @reference.blank? %>
</div>

<% if params[:iframe] != '1' %>
<ul class="nav nav-pills">
<% if can? :edit, @application %>
<li>
	<%= link_to 'Edit', edit_application_path(@application), :class => "btn btn-default" %>
</li>
<% end %>
<li>
	<%= link_to 'Back', applications_path, :class => "btn btn-default"%>
</li>
</ul>
<% end %>

app/views/applications/sign.js.erb
$("#signature_status").html('<%=glyph("ok") %>');
$.each(tinyMCE.editors, function(i,v) {v.getBody().setAttribute('contenteditable',false)  });
$("#sign_action_button").attr("href","<%=unsign_application_path%>").html("Unsign Application");
$("#flash_message").html('<%=flash_message(flash)%>');
$("body").scrollTop(0);
$("input,select,textarea").attr("disabled","true")
$("#sign_action_button").removeAttr("disabled")
window.setTimeout(function() { $(".alert-dismissable").alert('close'); }, 2000);
signed = true;

app/views/applications/unsign.js.erb
$("#signature_status").html('<%=glyph("exclamation-sign") %>');
$("#sign_action_button").attr("href","<%=sign_application_path%>").html("Sign Application");
$("#flash_message").html('<%=flash_message(flash)%>');
$("body").scrollTop(0);
$.each(tinyMCE.editors, function(i,v) {v.getBody().setAttribute('contenteditable',true)  });
$("input,select,textarea").removeAttr("disabled");
window.setTimeout(function() { $(".alert-dismissable").alert('close'); }, 2000);
signed = false;