config/routes.rb
Scholarships::Application.routes.draw do
  resources :scores


  resources :references


  resources :applications do
    collection do
      post :edit_multiple
    end
  end

  match '/applications/:id/sign', to: 'applications#sign', as: :sign_application
  match '/applications/:id/unsign', to: 'applications#unsign', as: :unsign_application
  match '/reset', to: 'applications#reset', as: :reset_applications_action


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  resources :users
  match '/references/send_email' => 'references#send_reference_request'
  match '/references/:id', to: 'references#resend', via: :post
  match '/references/token/:token' => 'references#edit'
  
 # match '/login' => "devise/sessions#new"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#  provider               :string(255)
#  uid                    :string(255)
#

class User < ActiveRecord::Base
  rolify
  has_and_belongs_to_many :applications
  has_many :references
  has_many :scores

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  after_create :default_role_and_create_blank_application

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name

  REVIEWERS = ['dcmanueljr@gmail.com','dtepfer@ameritech.net','sthoron@aol.com','swansj@gmail.com','dsanchez@pflag.org','jennifersavage@pflagtricities.org',
                'mosestorreblanca@gmail.com','katynelsen71@gmail.com','lynne_490@hotmail.com','madams4@hotmail.com','kt6565@yahoo.com','hrickerl1@gmail.com',
                'laurie.mayers@gmail.com','thom3308@msn.com','arthurfreeheart1@gmail.com','patpoynter@yahoo.com', 'sherrythompsonharrold@gmail.com', 'tamiekaufman@hotmail.com',
                'pflagyumasecretary@yahoo.com', 'cztwins@hotmail.com', 'hughes1985@hotmail.com', 'taramitchell@gmail.com']

  DEADLINE = Date::strptime(ENV['DEADLINE'],"%m-%d-%Y")

  def is?(role)
    self.has_role?(role)
  end

  def application
    if self.has_role? :student
      Application.find_by_uid(self.id)
    end
  end


  def incomplete_application?
    !@email.in? REVIEWERS and self.application.incomplete? unless self.application.blank?
  end

  def active_for_authentication?
    super and !(self.is? :student and Date.today > DEADLINE )
  end

  def inactive_message
    Date.today <= DEADLINE ? super : :deadline_has_already_passed
  end

  private
  def default_role_and_create_blank_application
    domain = /@(.+$)/.match(self.email)[1]
    admin = domain.casecmp("pflag.org") != 0 ? false : true
#    admin = false #no auto admin
    reviewer = self.email.downcase.in? User::REVIEWERS #|| domain.casecmp("pflag.org") == 0 # add PFLAG.org as reviewers

    if reviewer
      remove_role :student
      add_role :reviewer
    elsif admin
      add_role :admin
    else
      add_role :student
      self.applications.push Application.new({:applicant_user_id => self.id}) unless Time.now.to_date > Date::strptime(ENV["DEADLINE"],"%m-%d-%Y")

    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  before_filter :authenticate_user!
  skip_authorize_resource :only => [:new, :create]
  load_and_authorize_resource
  before_filter :filter_users, :only => :index

  
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'

    if request.format.to_sym == :html
      @users = @users.paginate(:page => params[:page]) 
    else
      @users = User.all
    end

    respond_to do |format|
      format.html #{ render action: "index", notice: @message}
      format.csv
    end

  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
  private
  def filter_users
    @users = @users.where("name ILIKE ?","%#{params[:name]}%") if params[:name].present?
    @users = @users.where("email ILIKE ?","%#{params[:email]}%") if params[:email].present?
    @users = @users.with_role(params[:role]) if params[:role].present?
    @users = @users.order("created_at desc") if params[:order] == 'registered_desc'
    @users = @users.order("created_at asc") if params[:order] == 'registered_asc'
    @users = @users.order("name asc") if params[:order] == 'name_asc'
    @users = @users.order("name desc") if params[:order] == 'name_desc'

  end
end

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :provider %>
  <%= f.input :uid %>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>User</h1>

<%= render 'form' %>

app/views/users/index.csv.erb
"name","email","student?","reviewer?","admin?"
<% @users.each do |u| %>"
<%= u.name %>","<%=u.email %>","<%= u.has_role? :student %>","<%= u.has_role? :reviewer %>","<%= u.has_role? :admin %>"
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">

<div class="well">
<%= simple_form_for '', :url => users_path, :method => :get, :html => { :class => "form-inline", :role => "form" } do |f| %>
  <%= f.input :name, :label => false, :wrapper_html => {:class=> "col-md-3"}, input_html: { value: params[:name], :placeholder => "Name"}, :required => false %>
  <%= f.input :email, :label => false, :wrapper_html => {:class=> "col-md-3"}, input_html: { value: params[:email], :placeholder => "Email"},  :required => false %>
  Reviewer <%= f.check_box :reviewers, :checked => (params[:reviewers] == '1') %> &nbsp;

  <%= f.button :submit, 'Search', :class => "btn btn-primary" %>
<p><br>
Showing <%= @users.count %> records
</p>

</div>

<%end%>

<%= will_paginate @applications, renderer: BootstrapPagination::Rails %>

<table class="table table-condensed">
  <thead>
    <tr>
      <th><%= link_to "Name", :order => (params[:order] == 'name_asc' ? 'name_desc' : "name_asc") %></th>
      <th></th>
      <th>Email</th>
      <th><%= link_to "Registered", :order => (params[:order] == 'registered_desc' ? 'registered_asc' : "registered_desc") %></th>
      <th># of Apps</th>
      <th># of Scores</th>
      <th>Role</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= link_to glyph("pencil"), edit_user_path(user) %></td>      
      <td><%= link_to user.email, "mailto:" + user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= link_to user.applications.count, applications_path(:user_id => user.id) %></td>
      <td><%= link_to user.scores.count, scores_path(:user_id => user.id) %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button"><%= user.roles.first.name.titleize unless user.roles.first.nil? %></a>
        <%= render user %>
      </td>
      <td><%= link_to(glyph("trash"), user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @applications, renderer: BootstrapPagination::Rails %>

</div>
<% if current_user.has_role? :admin %>
    <%= link_to "Download CSV", users_path(:format => :csv), :class => 'btn btn-primary'  %>
<%end%>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= link_to "#{@user.email}", "mailto:#{@user.email}" if @user.email %></p>
<p>Applications:
<% @user.applications.each do |a| %>
	<%= link_to a.id, application_path(a.id) %>&nbsp;
<% end %>
<p>References:
<% @user.references.each do |r| %>
	<%= link_to r.id, reference_path(r.id) %>&nbsp;
<% end %>


</p>