config/routes.rb
Scholarships::Application.routes.draw do
  resources :scores


  resources :references


  resources :applications do
    collection do
      post :edit_multiple
    end
  end

  match '/applications/:id/sign', to: 'applications#sign', as: :sign_application
  match '/applications/:id/unsign', to: 'applications#unsign', as: :unsign_application
  match '/reset', to: 'applications#reset', as: :reset_applications_action


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  resources :users
  match '/references/send_email' => 'references#send_reference_request'
  match '/references/:id', to: 'references#resend', via: :post
  match '/references/token/:token' => 'references#edit'
  
 # match '/login' => "devise/sessions#new"

end

app/models/reference.rb
# == Schema Information
#
# Table name: references
#
#  id                               :integer          not null, primary key
#  application_id                   :integer
#  name                             :string(255)
#  email                            :string(255)
#  phone_number                     :string(255)
#  how_long_have_you_known          :string(255)
#  relationship                     :text
#  references_essay                 :text
#  created_at                       :datetime         not null
#  updated_at                       :datetime         not null
#  user_id                          :integer
#  completed                        :datetime
#  token                            :string(255)
#  maturity                         :integer
#  leadership_ability               :integer
#  self_confidence                  :integer
#  self_awareness                   :integer
#  intellectual_curiosity           :integer
#  initiative                       :integer
#  adaptability                     :integer
#  personal_integrity               :integer
#  respect_for_different_viewpoints :integer
#

class Reference < ActiveRecord::Base
  attr_accessible :application_id, :email, :how_long_have_you_known, :name, :phone_number, :references_essay, :relationship, :maturity, :leadership_ability, :self_confidence, :self_awareness, :intellectual_curiosity, :initiative, :adaptability, :personal_integrity, :respect_for_different_viewpoints
  belongs_to :application
  belongs_to :user
  before_save :downcase_email
  RATING_SCALE = [['Excellent',4],['Above Average',3],['Average',2], ['Below Average',1], ['Inadequate Opportunity to Observe',0]]
  RATINGS_HASH = {4=>"Excellent", 3=>"Above Average", 2=>"Average", 1=>"Below Average", 0=>"Inadequate Opportunity to Observe"}
  scope :completed, where("completed IS NOT NULL")
  scope :incomplete, where("completed IS NULL")
  def downcase_email
  	self.email = self.email.downcase
  end

  def token_url
    "/references/token/#{self.token}"
  end

end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  # GET /references
  # GET /references.json
  load_and_authorize_resource
  skip_authorize_resource :only => [:edit, :update]
  skip_authorization_check :only => [:edit, :update]
  before_filter :filter_references, :only => :index

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @references }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    @reference = Reference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/new
  # GET /references/new.json
  def new
    @reference = Reference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/1/edit
  def edit
    @reference = Reference.find_by_token(params[:token])
    if @reference.nil? and !current_user.is? :admin
      redirect_to root_url, error: "Invalid Reference"
    elsif current_user.present? and current_user.is? :admin
      @reference = (Reference.find(params[:id]) unless(params[:id].blank?)) || Reference.find_by_token(params[:token])
    end
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(params[:reference])

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render json: @reference, status: :created, location: @reference }
      else
        format.html { render action: "new" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /references/1
  # PUT /references/1.json
  def update
    @reference = Reference.find(params[:id])
    @reference.completed = Time.new

    respond_to do |format|
      if @reference.update_attributes(params[:reference])
        ReferenceMailer.reference_confirmation_email(@reference).deliver
        format.html { redirect_to root_url, notice: 'Thank you for submitting your reference.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  def resend
    @reference = Reference.find(params[:id])

    respond_to do |format|

      if !@reference.nil?
        ReferenceMailer.send_reference_request_email(@reference).deliver
        format.html { redirect_to references_url, notice: 'Reference request was successfully resent.'  }

      else
        format.html { redirect_to references_url, notice: 'Reference request failed.'  }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end

  end

  def send_reference_request
    @reference = Reference.find_by_user_id_and_email(params[:reference][:user_id] || current_user.id,params[:reference][:email]) || Reference.new

    if @reference.token.blank?
      @reference.token = Array.new(32){[*'0'..'9', *'a'..'z', *'A'..'Z'].sample}.join
      @reference.user = (User.find(params[:reference][:user_id]) unless params[:reference][:user_id].blank?) || current_user
      @reference.email = params[:reference][:email]
      @reference.application = Application.find_by_applicant_user_id(params[:reference][:user_id] || current_user)
    end

    respond_to do |format|
      if @reference.save
          ReferenceMailer.send_reference_request_confirmation_email(@reference).deliver
          ReferenceMailer.send_reference_request_email(@reference).deliver
          format.html { redirect_to references_url, notice: 'Reference request was successfully sent.'  }
      else
          format.html { redirect_to references_url, notice: 'Reference request failed.'  }
          format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference = Reference.find(params[:id])
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url }
      format.json { head :no_content }
    end
  end
  private
  def filter_references
    @references = @references.accessible_by(current_ability)
    @references = @references.where(application_id: params[:application_id]) if params[:application_id].present?
    @references = @references.where(user_id: params[:user_id]) if params[:user_id].present?
    @references = @references.where("email ILIKE ?","%#{params[:email]}%")if params[:email].present?

  end

end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_fields.html.erb
<p>
  <b>Name:</b>
  <%= @reference.name %>
</p>


<% if current_user.is? :admin %>
<p><b><%= link_to "Private Edit Link", @reference.token_url %></b>
  
</p>
<p>
  <b>Email:</b>
  <%= link_to @reference.email, "mailto:#{@reference.email}"%>
</p>

<p>
  <b>Phone number:</b>
  <%= @reference.phone_number %>
</p>
<% end %>
<p>
  <b>How long have you known:</b>
  <%= @reference.how_long_have_you_known %>
</p>

<p>
  <b>Relationship:</b>
  <%= @reference.relationship %>
</p>

<p>
  <b>References essay:</b>
  <%= @reference.references_essay.html_safe unless @reference.references_essay.blank? %>
</p>

<h3>Reference Ratings</h3>
<p>References are asked to rate the applicant on the qualities below. They are able to select Excellent, Above Average, Average, Below Average or Inadequate Opportunity to Observe in their ratings.</p>
<table class="table-striped table">
<thead><tr><th>Category</th><th>Rating</th></tr></thead>
<tbody>
<tr><td>Maturity</td><td><%=Reference::RATINGS_HASH[@reference.maturity]%></td></tr>
<tr><td>Leadership Ability</td><td><%=Reference::RATINGS_HASH[@reference.leadership_ability]%></td></tr>
<tr><td>Self Confidence</td><td><%=Reference::RATINGS_HASH[@reference.self_confidence]%></td></tr>
<tr><td>Self Awareness</td><td><%=Reference::RATINGS_HASH[@reference.self_awareness]%></td></tr>
<tr><td>Intellectual Curiosity</td><td><%=Reference::RATINGS_HASH[@reference.intellectual_curiosity]%></td></tr>
<tr><td>Initiative</td><td><%=Reference::RATINGS_HASH[@reference.initiative]%></td></tr>
<tr><td>Adaptability</td><td><%=Reference::RATINGS_HASH[@reference.adaptability]%></td></tr>
<tr><td>Personal Integrity</td><td><%=Reference::RATINGS_HASH[@reference.personal_integrity]%></td></tr>
<tr><td>Respect for Different Viewpoints</td><td><%=Reference::RATINGS_HASH[@reference.respect_for_different_viewpoints]%></td></tr>

</tbody>
</table>

app/views/references/_form.html.erb
<%= simple_form_for(@reference) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div>
      <b>Student Name: </b><%= @reference.user.name unless @reference.user.blank? %>
    </div>
    <% if current_user.present? and current_user.is? :admin %>
    <p><b><%= link_to "Private Edit Link", @reference.token_url %></b>

    </p>
    <p>
      <b>Email:</b>
      <%= link_to @reference.email, "mailto:#{@reference.email}"%>
    </p>

    <p>
      <b>Phone number:</b>
      <%= @reference.phone_number %>
    </p>
    <% end %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.input :how_long_have_you_known%>
    <%= f.input :relationship, :as => :string  %>
    <h3>Please Rank The Applicant In Each of The Following Areas</h3>
    <table class="table table-striped">
    <thead>
      <tr>
      <th>
        &nbsp;
      </th>
      <% Reference::RATING_SCALE.each do |rating| %>
        <th><%= rating[0] %></th>
      <% end %>
      </tr>
    </thead>
    <tbody>
    <% rating_fields = [:maturity, :leadership_ability, :self_confidence, :self_awareness, :intellectual_curiosity, :initiative, :adaptability, :personal_integrity, :respect_for_different_viewpoints]; %>
    <% rating_fields.each do |field| %>
      <%= rating_row(field,f) %>
    <% end %>
    </tbody>
    </table>

    <%= f.input :references_essay, :as => :tinymce %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-default" %> <%= link_to "Delete", f.object, class: 'btn btn-danger', data: {method: 'DELETE'}, confirm: "Are you sure you want to delete the reference?"  if can? :delete, f.object %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>PFLAG National Scholarship Reference Form</h1>

<%= render 'form' %>

app/views/references/index.html.erb
<h1>My References</h1>
<p>You may send more than one reference request, but only one reference will be accepted.</p><p>You may cancel a reference request by clicking the <%=glyph("trash")%> icon.</p>
<table class="table table-striped">
  <tr>
    <% if current_user.has_role? :admin %>
    <th>Applicant</th>
    <% end %>
    <th>Email</th>
    <th>Name</th>
    <th>Completed</th>
    <th></th>
  </tr>

<h2>Completed References: <%= @references.select{|s| s.completed.present? }.count %></h2>

<% @references.each do |reference| %>
  <tr>
    <% if current_user.has_role? :admin %>
    <td><%= link_to reference.application.user.name, user_path(reference.user) unless reference.application.blank? || reference.application.user.blank? %></td>
    <% end %>
    <td><%= link_to reference.email, "mailto:#{reference.email}" %></td>
    <td><%= reference.name %></td>
    <td><% if reference.completed %>
            <%=glyph("ok") %>
          <% else %>
            <%=glyph("exclamation-sign") %>&nbsp;
            <%= (link_to glyph("send"), reference, action: :resend, method: :resend) unless reference.completed.present? %>
          <% end %>
    </td>
    <td>
    <%= link_to glyph("trash"), reference, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% if can? :edit, reference %>&nbsp;
      <%= link_to glyph("pencil"), edit_reference_path(reference)  %><% end %></td>

  </tr>
<% end %>
</table>

<% if (@references.select{|s| s.completed.present? }.count == 0 or current_user.has_role? :admin ) %>
  <div class="well">
  <%= simple_form_for :reference, :url => references_send_email_path, :method => :post do |f| %>
    <%= (f.input :user_id, :collection => User.order(:name), :label_method => :name,:value_method => :id) if current_user.has_role? :admin %>
    <%= f.input :email %>
    <%= f.submit "Send Reference Request", :class => "btn btn-primary" %>
  <% end %>
  </div>
<% end %>

app/views/references/new.html.erb
<h1>New reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Application:</b>
	<% if can? :view, @reference.application%>
	  <%= link_to "#{@reference.application.user.name}", application_path(@reference.application_id) unless @reference.application.blank? or @reference.application.user.blank? %>
	<% else %>
	  <%= "#{@reference.application.user.name} (#{@reference.application_id})" unless @reference.application.blank? or @reference.application.user.blank?%>
	<% end %>
</p>
<%= render "fields" %>


<% if can? :edit, @reference %>
  <%= link_to 'Edit', edit_reference_path(@reference), :class => "btn btn-default" %>
<% end %>