config/routes.rb
Scholarships::Application.routes.draw do
  resources :scores


  resources :references


  resources :applications do
    collection do
      post :edit_multiple
    end
  end

  match '/applications/:id/sign', to: 'applications#sign', as: :sign_application
  match '/applications/:id/unsign', to: 'applications#unsign', as: :unsign_application
  match '/reset', to: 'applications#reset', as: :reset_applications_action


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  resources :users
  match '/references/send_email' => 'references#send_reference_request'
  match '/references/:id', to: 'references#resend', via: :post
  match '/references/token/:token' => 'references#edit'
  
 # match '/login' => "devise/sessions#new"

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 2.3 %>
<div id="flash_message" class="col-md-12">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissable alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<% if params[:iframe] != '1' %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><%= image_tag "logo.png", :width=>"25px" %></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <%= render 'layouts/navigation_links' %>
    </ul>

  </div><!-- /.navbar-collapse -->
</nav>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <% if current_user.has_role? :student %>
        <% if Application.find_by_uid(current_user.id).present? %>
            <li><%= link_to 'My Application', edit_application_path(Application.find_by_uid(current_user.id)) %></li>
        <% else %>
            <li><%= link_to 'My Application', new_application_path %></li>
        <% end %>
        <li><%= link_to 'My References', references_path %></li>
    <% end %>
    <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <% if current_user.has_role? :reviewer %>
        <li><%= link_to 'Applications', applications_path %></li>
        <li><%= link_to 'Scores', scores_path %></li>
    <% end %>
    <% if current_user.has_role? :admin %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Applications <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><%= link_to 'All', applications_path %></li>
            <li class="divider"></li>
              <li><%= link_to 'Completed', applications_path(:signed => 1, :transcript => 1, :essay => 1, :reference => 1 )%></li>
            <li class="divider"></li>
            <li><%= link_to 'For My Review', applications_path(:user_id => current_user.id )%></li>

          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Users', users_path(:order => "registered_desc") %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Students', users_path(:role => "student") %>
            </li>
            <li>
              <%= link_to 'Reviewers', users_path(:role => "reviewer") %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'References', references_path %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Reset for Next Year', reset_applications_action_path %>
            </li>
          </ul>
        </li>
    <% end %>
<% else #not signed in%>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scholarships" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Scholarships" %>">
    <link rel="apple-touch-icon" href="apple-touch-icon.png"/>
    <link rel="icon" href="favicon.ico" />
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= tinymce %>
  </head>
  <body>
    <%# application layout styled for Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="<%="#{controller_name} #{action_name}"%>">
      <div class="container">
        <div class="content">
           <div class="row">
              <%= render 'layouts/messages' %>
          </div>
          <div class="row">
              <%= yield %>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/pflag_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
    	<style type="text/css">
<!--
/* Client-specific Styles */
			#outlook a{padding:0;} /* Force Outlook to provide a "view in browser" button. */
			body{width:100% !important;} .ReadMsgBody{width:100%;} .ExternalClass{width:100%;} /* Force Hotmail to display emails at full width */
			body{-webkit-text-size-adjust:none;} /* Prevent Webkit platforms from changing default text sizes. */
			
			/* Reset Styles */
			body{margin:0; padding:0;}
			img{border:0; height:auto; line-height:100%; outline:none; text-decoration:none;}
			table td{border-collapse:collapse;}
			#backgroundTable{height:100% !important; margin:0; padding:0; width:100% !important;}
			
			/* Template Styles */
			
			/* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: COMMON PAGE ELEMENTS /\/\/\/\/\/\/\/\/\/\ */

			/**
			* @tab Page
			* @section background color
			* @tip Set the background color for your email. You may want to choose one that matches your company's branding.
			* @theme page
			*/
			body, #backgroundTable{
				/*@editable*/ background-color:#FAFAFA;
			}

			/**
			* @tab Page
			* @section email border
			* @tip Set the border for your email.
			*/
			#templateContainer{
				/*@editable*/ border: 1px solid #DDDDDD;
			}

			/**
			* @tab Page
			* @section heading 1
			* @tip Set the styling for all first-level headings in your emails. These should be the largest of your headings.
			* @style heading 1
			*/
			h1, .h1{
				/*@editable*/ color:#202020;
				display:block;
				/*@editable*/ font-family:Arial;
				/*@editable*/ font-size:34px;
				/*@editable*/ font-weight:bold;
				/*@editable*/ line-height:100%;
				margin-top:0;
				margin-right:0;
				margin-bottom:10px;
				margin-left:0;
				/*@editable*/ text-align:left;
			}

			/**
			* @tab Page
			* @section heading 2
			* @tip Set the styling for all second-level headings in your emails.
			* @style heading 2
			*/
			h2, .h2{
				/*@editable*/ color:#202020;
				display:block;
				/*@editable*/ font-family:Arial;
				/*@editable*/ font-size:30px;
				/*@editable*/ font-weight:bold;
				/*@editable*/ line-height:100%;
				margin-top:0;
				margin-right:0;
				margin-bottom:10px;
				margin-left:0;
				/*@editable*/ text-align:left;
			}

			/**
			* @tab Page
			* @section heading 3
			* @tip Set the styling for all third-level headings in your emails.
			* @style heading 3
			*/
			h3, .h3{
				/*@editable*/ color:#202020;
				display:block;
				/*@editable*/ font-family:Arial;
				/*@editable*/ font-size:26px;
				/*@editable*/ font-weight:bold;
				/*@editable*/ line-height:100%;
				margin-top:0;
				margin-right:0;
				margin-bottom:10px;
				margin-left:0;
				/*@editable*/ text-align:left;
			}

			/**
			* @tab Page
			* @section heading 4
			* @tip Set the styling for all fourth-level headings in your emails. These should be the smallest of your headings.
			* @style heading 4
			*/
			h4, .h4{
				/*@editable*/ color:#202020;
				display:block;
				/*@editable*/ font-family:Arial;
				/*@editable*/ font-size:22px;
				/*@editable*/ font-weight:bold;
				/*@editable*/ line-height:100%;
				margin-top:0;
				margin-right:0;
				margin-bottom:10px;
				margin-left:0;
				/*@editable*/ text-align:left;
			}
			
			/* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: PREHEADER /\/\/\/\/\/\/\/\/\/\ */

			/**
			* @tab Header
			* @section preheader style
			* @tip Set the background color for your email's preheader area.
			* @theme page
			*/
			#templatePreheader{
				/*@editable*/ background-color:#FAFAFA;
			}

			/**
			* @tab Header
			* @section preheader text
			* @tip Set the styling for your email's preheader text. Choose a size and color that is easy to read.
			*/
			.preheaderContent div{
				/*@editable*/ color:#505050;
				/*@editable*/ font-family:Arial;
				/*@editable*/ font-size:10px;
				/*@editable*/ line-height:100%;
				/*@editable*/ text-align:left;
			}

			/**
			* @tab Header
			* @section preheader link
			* @tip Set the styling for your email's preheader links. Choose a color that helps them stand out from your text.
			*/
			.preheaderContent div a:link, .preheaderContent div a:visited, /* Yahoo! Mail Override */ .preheaderContent div a .yshortcuts /* Yahoo! Mail Override */{
				/*@editable*/ color:#336699;
				/*@editable*/ font-weight:normal;
				/*@editable*/ text-decoration:underline;
			}

			/* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: HEADER /\/\/\/\/\/\/\/\/\/\ */

			/**
			* @tab Header
			* @section header style
			* @tip Set the background color and border for your email's header area.
			* @theme header
			*/
			#templateHeader{
				/*@editable*/ background-color:#FFFFFF;
				/*@editable*/ border-bottom:0;
			}

			/**
			* @tab Header
			* @section header text
			* @tip Set the styling for your email's header text. Choose a size and color that is easy to read.
			*/
			.headerContent{
				/*@editable*/ color:#202020;
				/*@editable*/ font-family:Arial;
				/*@editable*/ font-size:34px;
				/*@editable*/ font-weight:bold;
				/*@editable*/ line-height:100%;
				/*@editable*/ padding:0;
				/*@editable*/ text-align:center;
				/*@editable*/ vertical-align:middle;
			}

			/**
			* @tab Header
			* @section header link
			* @tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.
			*/
			.headerContent a:link, .headerContent a:visited, /* Yahoo! Mail Override */ .headerContent a .yshortcuts /* Yahoo! Mail Override */{
				/*@editable*/ color:#336699;
				/*@editable*/ font-weight:normal;
				/*@editable*/ text-decoration:underline;
			}

			#headerImage{
				height:auto;
				max-width:600px;
			}

			/* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: MAIN BODY /\/\/\/\/\/\/\/\/\/\ */

			/**
			* @tab Body
			* @section body style
			* @tip Set the background color for your email's body area.
			*/
			#templateContainer, .bodyContent{
				/*@editable*/ background-color:#FFFFFF;
			}
			
			/**
			* @tab Body
			* @section body text
			* @tip Set the styling for your email's main content text. Choose a size and color that is easy to read.
			* @theme main
			*/
			.bodyContent div{
				/*@editable*/ color:#505050;
				/*@editable*/ font-family:Arial;
				/*@editable*/ font-size:14px;
				/*@editable*/ line-height:150%;
				/*@editable*/ text-align:left;
			}
			
			/**
			* @tab Body
			* @section body link
			* @tip Set the styling for your email's main content links. Choose a color that helps them stand out from your text.
			*/
			.bodyContent div a:link, .bodyContent div a:visited, /* Yahoo! Mail Override */ .bodyContent div a .yshortcuts /* Yahoo! Mail Override */{
				/*@editable*/ color:#336699;
				/*@editable*/ font-weight:normal;
				/*@editable*/ text-decoration:underline;
			}
			
			.bodyContent img{
				display:inline;
				height:auto;
			}
			
			/* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: FOOTER /\/\/\/\/\/\/\/\/\/\ */
			
			/**
			* @tab Footer
			* @section footer style
			* @tip Set the background color and top border for your email's footer area.
			* @theme footer
			*/
			#templateFooter{
				/*@editable*/ background-color:#FFFFFF;
				/*@editable*/ border-top:0;
			}
			
			/**
			* @tab Footer
			* @section footer text
			* @tip Set the styling for your email's footer text. Choose a size and color that is easy to read.
			* @theme footer
			*/
			.footerContent div{
				/*@editable*/ color:#707070;
				/*@editable*/ font-family:Arial;
				/*@editable*/ font-size:12px;
				/*@editable*/ line-height:125%;
				/*@editable*/ text-align:left;
			}
			
			/**
			* @tab Footer
			* @section footer link
			* @tip Set the styling for your email's footer links. Choose a color that helps them stand out from your text.
			*/
			.footerContent div a:link, .footerContent div a:visited, /* Yahoo! Mail Override */ .footerContent div a .yshortcuts /* Yahoo! Mail Override */{
				/*@editable*/ color:#336699;
				/*@editable*/ font-weight:normal;
				/*@editable*/ text-decoration:underline;
			}
			
			.footerContent img{
				display:inline;
			}
			
			/**
			* @tab Footer
			* @section social bar style
			* @tip Set the background color and border for your email's footer social bar.
			* @theme footer
			*/
			#social{
				/*@editable*/ background-color:#FAFAFA;
				/*@editable*/ border:0;
			}
			
			/**
			* @tab Footer
			* @section social bar style
			* @tip Set the background color and border for your email's footer social bar.
			*/
			#social div{
				/*@editable*/ text-align:center;
			}
			
			/**
			* @tab Footer
			* @section utility bar style
			* @tip Set the background color and border for your email's footer utility bar.
			* @theme footer
			*/
			#utility{
				/*@editable*/ background-color:#FFFFFF;
				/*@editable*/ border:0;

			}

			/**
			* @tab Footer
			* @section utility bar style
			* @tip Set the background color and border for your email's footer utility bar.
			*/
			#utility div{
				/*@editable*/ text-align:center;
			}
-->
</style>
</head>
<body>
<table border="0" cellpadding="0" cellspacing="0" id="backgroundTable" style="width: 100%; height: 100%;">
	<tbody>
		<tr>
			<td align="center" valign="top">
				<table border="0" cellpadding="0" cellspacing="0" id="templateContainer" style="width: 600px;">
					<tbody>
						<tr>
							<td align="center" valign="top">
								<img alt="PFLAG Email" height="108" src="https://community.pflag.org/view.image?Id=404" width="600" /></td>
						</tr>
						<tr>
							<td align="center" valign="top">
								<table border="0" cellpadding="0" cellspacing="0" id="templateBody" style="width: 600px;">
									<tbody>
										<tr>
											<td class="bodyContent" valign="top">
												<%= yield %>

											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td align="center" valign="top">
								<table border="0" cellpadding="10" cellspacing="0" id="templateFooter" style="width: 600px;">
									<tbody>
										<tr>
											<td class="footerContent" valign="top">
												<table border="0" cellpadding="10" cellspacing="0" style="width: 569px; height: 187px;">
													<tbody>
														<tr>
															<td valign="top" width="350">
																<div style="text-align: center;">
																	<span style="color: #501f59; font-family: 'arial black', 'avant garde'; font-size: 10pt; text-align: left;">CONNECT WITH US ONLINE!</span></div>
																<table border="0" cellpadding="10" cellspacing="0" style="cursor: default; border: 1px dashed #bbbbbb; font-family: 'Lucida Sans Unicode', Verdana, sans-serif; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; width: 574px;">
																	<tbody>
																		<tr>
																			<td style="text-align: center;" valign="top" width="350">
																				<a href="http://www.facebook.com/pflag"><img alt="Like us on Facebook" height="50" src="https://community.pflag.org/view.image?Id=3604" style="border: 0px; height: auto; line-height: 12px; outline: none; text-decoration: none; display: inline;" width="50" /></a></td>
																			<td style="text-align: center;" valign="top" width="350">
																				<a href="http://www.twitter.com/pflag"><img alt="Follow us on Twitter" height="50" src="https://community.pflag.org/view.image?Id=3610" style="border: 0px; height: auto; line-height: 12px; outline: none; text-decoration: none; display: inline;" width="50" /></a></td>
																			<td style="text-align: center;" valign="top" width="350">
																				<a href="http://www.youtube.com/pflagnational"><img alt="Watch us on YouTube" height="50" src="https://community.pflag.org/view.image?Id=3611" style="border: 0px; height: auto; line-height: 12px; outline: none; text-decoration: none; display: inline;" width="50" /></a></td>
																			<td style="text-align: center;" valign="top" width="190">
																				<a href="http://www.instagram.com/pflagnational"><img alt="Follow us on Instagram" height="50" src="https://community.pflag.org/view.image?Id=3607" style="border: 0px; height: auto; line-height: 12px; outline: none; text-decoration: none; display: inline;" width="50" /></a></td>
																			<td style="text-align: center;" valign="top" width="190">
																				<a href="http://www.pinterest.com/pflag"><img alt="Pin to us on Pinterest" height="50" src="https://community.pflag.org/view.image?Id=3609" style="border: 0px; height: auto; line-height: 12px; outline: none; text-decoration: none; display: inline;" width="50" /></a></td>
																		</tr>
																	</tbody>
																</table>
																<div style="text-align: center;">
																	<em>Copyright &copy; 2014 PFLAG National, All rights reserved.</em></div>
																<div style="text-align: center;">
																	PFLAG NATIONAL<br />
																	1828 L ST NW STE 660<br />
																	Washington, DC 20036-5112</div>
															</td>
														</tr>
														<tr>
															<td id="utility" valign="middle">
													
															</td>
														</tr>
													</tbody>
												</table>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>
</body>
</html>